spring:
  application:
    name: knowledge-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/support_db}
    username: ${SPRING_DATASOURCE_USERNAME:support_user}
    password: ${SPRING_DATASOURCE_PASSWORD:support_pass}
  jpa:
    hibernate:
      ddl-auto: update   # use validate or none in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: 6379
  cache:
    type: redis

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: knowledge-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.support.*,java.util"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    ticket-events: ticket-events
    knowledge-events: knowledge-events
